services:
  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    networks:
      - docker-network
    restart: on-failure
    volumes:
      - /Users/aldokezer/orezek/data/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      - WORDPRESS_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_USER
    env_file:
      - .env
    networks:
      - docker-network
    restart: on-failure
    volumes:
      - /Users/aldokezer/orezek/data/wp_data:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - docker-network
    restart: on-failure
    volumes:
      - /Users/aldokezer/orezek/data/wp_data:/var/www/html
      - /Users/aldokezer/orezek/data/ssl:/etc/ssl/certs
      - /Users/aldokezer/orezek/data/ssl:/etc/ssl/private

networks:
  docker-network:
    driver: bridge


# secrets:
#   mysql_root_password:
#     file: ../secrets/mysql_root_password.txt
#   mysql_user_password:
#     file: ../secrets/mysql_user_password.txt
#   wp_admin_password:
#     file: ../secrets/wp_admin_password.txt
#   wp_user_password:
#     file: ../secrets/wp_user_password.txt
#   ssl_certificate_crt:
#     file: ../secrets/certificates/server.crt
#   ssl_certificate_key:
#     file: ../secrets/certificates/server.key

