services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: "mariadb:1.0"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - mysql_root_password
      - mysql_user_password
    networks:
      - inception-network
    restart: on-failure
    volumes:
      - ~/orezek/data/mysql_data:/var/lib/mysql
  wordpress:
    build:
      context: ./requirements/wordpress
    image: "wordpress:1.0"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_ADMIN_FIRST_NAME: ${WORDPRESS_ADMIN_FIRST_NAME}
      WORDPRESS_ADMIN_LAST_NAME: ${WORDPRESS_ADMIN_LAST_NAME}
      WORDPRESS_EDITOR_USER: $WORDPRESS_EDITOR_USER}
      WORDPRESS_EDITOR_EMAIL: ${WORDPRESS_EDITOR_EMAIL}
      WORDPRESS_EDITOR_FIRST_NAME: ${WORDPRESS_EDITOR_FIRST_NAME}
      WORDPRESS_EDITOR_LAST_NAME: ${WORDPRESS_EDITOR_LAST_NAME}
    depends_on:
      - mariadb
    secrets:
      - mysql_root_password
      - mysql_user_password
      - wp_admin_password
      - wp_db_password
      - wp_editor_password
    networks:
      - inception-network
    restart: on-failure
    volumes:
      - ~/orezek/data/wp_data:/var/www/html
  nginx:
    build:
      context: ./requirements/nginx
    image: "nginx:1.0"
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: on-failure
    volumes:
      - ~/orezek/data/wp_data:/var/www/html
      - ../secrets/certificates:/etc/ssl/certs
      - ../secrets/certificates:/etc/ssl/private

networks:
  inception-network:
    driver: bridge


secrets:
# Mariadb
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_user_password:
    file: ../secrets/mysql_user_password.txt
# Wordpress application
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
# WP database password - from wordpress app to wordpress db in mariadb
  wp_db_password:
    file: ../secrets/wp_db_password.txt
# Second WP user password (after admin)
  wp_editor_password:
    file: ../secrets/wp_editor_password.txt
# Certificates
  ssl_certificate_crt:
    file: ../secrets/certificates/server.crt
  ssl_certificate_key:
    file: ../secrets/certificates/server.key

